---
- name: "Packer file creator"
  hosts: localhost
  connection: local

  vars_files:
    - vars/vars.yml

  tasks:
#    - import_tasks: tasks/testing.yml
    - import_tasks: tasks/build_setup.yml
    - import_tasks: tasks/packer_creation.yml
    - import_tasks: tasks/spin_up_vm.yml
