---
- name: Run builder_setup.py script
  script: "{{ pwd }}/scripts/builder_setup.py {{ os_family }} {{ item }} {{ vm_memory }} {{ vm_cpu_num }} {{ vm_disk_size }} {{ pwd }}"
  args:
    executable: python3
  with_items:
    - "{{ vm_name }}"
- name: Run builder_merge.py script
  script: "{{ pwd }}/scripts/builder_merge.py {{ os_family }} {{ os_name }} {{ build_version }} {{ vm_name|join(' ') }}"
  args:
    executable: python3
- name: Validate Packer file
  command: packer validate {{ pwd }}/{{ os_family }}/{{ os_name }}_packer_{{ build_version }}.json
  register: result
