---
- name: Execute order 66
  command: packer build {{ pwd }}/packer_templates/{{ os_family }}/{{ os_name }}_packer_{{ build_version }}.json
  args:
    chdir: "{{ pwd }}/packer_templates/{{ os_family }}/"
